version: '3.9'
services:
    test:
        build: .
        ports:
            - "5001-5007:5001"
        volumes:
            - .:/code

        environment:
            DB_UPSTREAM: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:5001
networks:
    default:
        name: my-net
        external: true

